name: Tests

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: "1.4.0"
    - name: Tests
      run: nimble test --threads:on --verbose -y

    - name: "try js"
      run: >
        nimble genjs
        && cd src/includes/ && yarn
        && ./node_modules/.bin/tsc
        && cd ../../
        && cp -v src/includes/calcit.procs.js js-out/calcit.procs.mjs
        && cp -v example/main.mjs js-out/
        && cp -v assets/webpack.config.js js-out/
        && cd js-out/ && yarn add webpack webpack-cli @calcit/ternary-tree
        && yarn webpack && node bundle.js
